spring.application.name=AtmosIQ

# PostgreSQl
spring.datasource.url=jdbc:postgresql://localhost:5432/SkySyncDB
spring.datasource.username=postgres
spring.datasource.password=rtekq46w@9926

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# OpenWeatherMap API Key
weather.api.key=3ce4bc0a43a2b3aecc355eb4caecd5d5