spring.application.name=AtmosIQ

# PostgreSQl
spring.datasource.url=jdbc:postgresql://localhost:5432/SkySyncDB
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# OpenWeatherClient API Key
weather.openweathermap.api-key=${OPENWEATHER_API_KEY}
weather.openweathermap.base-url=https://api.openweathermap.org/data/2.5/weather

# WeatherAPI
weather.weatherapi.api-key=${WEATHER_API}
weather.weatherapi.base-url=https://api.weatherapi.com/v1/current.json

spring.profiles.active=local

# Schedular - 10 minutes = 600000 ms
# Yeh ek configurable value hai jo dono jagah use hoti hai — scheduler ki speed aur service ka freshness check.
schedular.refresh-interval-ms=30000